# PFNApp hardened image for PocketBase
# NOTE: Base OS type is unknown or distroless/scratch.
# Standard package manager upgrade is not applicable.
# This image is re-published as-is from upstream.
# CVE reduction depends on upstream releasing a new version.
FROM ghcr.io/muchobien/pocketbase:0.40.4
