# PFNApp hardened image for FileBrowser
# NOTE: Base OS type is unknown or distroless/scratch.
# Standard package manager upgrade is not applicable.
# This image is re-published as-is from upstream.
# CVE reduction depends on upstream releasing a new version.
FROM docker.io/filebrowser/filebrowser:v2.63.23
